inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 140

Metrics/ModuleLength:
  Exclude:
    - 'lib/blizzard_api/wow.rb'

Metrics/AbcSize:
  Max: 20

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'